### ISSUE TITLE
Compatibility isssue with RTAutoSprintEX

### ISSUE THREAD

**Issue by RetroNutcase** [TheTimeSweeper/the#10]
Mod in question:
https://thunderstore.io/package/JohnEdwa/RTAutoSprintEx/2.1.2/

If you have auto sprint enabled, Tesla's secondary goes off instantly instead of letting you aim it if you try to use it while sprinting.

**Comment by TheTimeSweeper** [comment]
thanks for letting me know, I'll take a look. In the meantime, you can use https://thunderstore.io/package/JohnEdwa/RTAutoSprintAddon/ to disable the state yourself. the state name is "ModdedEntityStates.TeslaTrooper.AimBigZap"

**Comment by TheTimeSweeper** [comment]
fixed a year later haha
