### ISSUE TITLE
Desolator: no rad point build up on damage ticks from R skills

### ISSUE THREAD

**Issue by Darkmega18** [TheTimeSweeper/the#12]
I noticed that the skills say irradiating, however when I'm punching radiation fields or my rad zones are placed down the enemies aren't generating rad stacks on themselves. only my gun and secondary deal rad stacks which makes it really hard to get any decent damage piled on. Is this intended? I'm guessing not?

**Comment by TheTimeSweeper** [comment]
issue was fixed on r2api's end a few days later. issue is being closed a year later :^)

**Comment by Darkmega18** [comment]
big oof.
