### ISSUE TITLE
Simplified Chinese translation

### ISSUE THREAD

**Issue by FallenTroop** [TheTimeSweeper/the#16]
Thank you for creating this mod, which makes people like me who love playing CNC series very happy. I provided a Chinese translation file at this URL. Also, I wonder if you have any ideas for adding other RA2 Units. Your mod is of high quality, and it would be a pity to leave it unfinished.

URL:
https://pan.quark.cn/s/95d60d1f007d

**Comment by FallenTroop** [comment]
> Thank you for creating this mod, which makes people like me who love playing CNC series very happy. I provided a Chinese translation file at this URL. Also, I wonder if you have any ideas for adding other RA2 Units. Your mod is of high quality, and it would be a pity to leave it unfinished.
> 
> Sorry, there are some issues. Please wait a moment before receiving the message.

**Comment by FallenTroop** [comment]
> Thank you for creating this mod, which makes people like me who love playing CNC series very happy. I provided a Chinese translation file at this URL. Also, I wonder if you have any ideas for adding other RA2 Units. Your mod is of high quality, and it would be a pity to leave it unfinished.
> 
> Sorry, there are some issues. Please wait a moment before receiving the message.

**Comment by FallenTroop** [comment]
Thank you for creating this mod, which makes people like me who love playing CNC series very happy. I provided a Chinese translation file at this URL. Also, I wonder if you have any ideas for adding other RA2 Units. Your mod is of high quality, and it would be a pity to leave it unfinished.

URL:https://pan.quark.cn/s/4a1f20a67ba8

**Comment by FallenTroop** [comment]
> Thank you for creating this mod, which makes people like me who love playing CNC series very happy. I provided a Chinese translation file at this URL. Also, I wonder if you have any ideas for adding other RA2 Units. Your mod is of high quality, and it would be a pity to leave it unfinished.
> 
> URL: https://pan.quark.cn/s/4a1f20a67ba8

**Comment by FallenTroop** [comment]
I'm sorry, the link above was lost due to some network issues. I'll send you a new one.
https://pan.quark.cn/s/4a1f20a67ba8

**Comment by FallenTroop** [comment]
Sorry, the link above was lost due to some network issues. I'll send you a new one.
New URL:   https://pan.quark.cn/s/4176dfa01d63

**Comment by TheTimeSweeper** [comment]
hey thanks thanks for doing this. both links don't work for me. Can you attach the files directly to the comment here?

**Comment by FallenTroop** [comment]
> hey thanks thanks for doing this. both links don't work for me. Can you attach the files directly to the comment here?

[cn Lang.zip](https://github.com/TheTimeSweeper/the/files/13310910/cn.Lang.zip)
is that so? I rarely use such features, maybe I'm doing it wrong.
