### ISSUE TITLE
Missile start position is too low for Tesla tower

### ISSUE THREAD

**Issue by apotsepko** [TheTimeSweeper/the#2]
![20220807161337_1](https://user-images.githubusercontent.com/25206470/183293187-8d16b141-b130-41f5-a7dd-4148e4fb356d.jpg)
![20220807161421_1](https://user-images.githubusercontent.com/25206470/183293219-5ae81402-ae4a-48fe-a08a-82f16fde91bd.jpg)
![20220807161509_1](https://user-images.githubusercontent.com/25206470/183293311-d5bba438-5528-475d-bc8f-22d86a6003a0.jpg)

Either move missile start position or make towers transparent for friendly fire (bad idea for Tesla trooper charge) !

**Comment by TheTimeSweeper** [comment]
I can't quite see what's going on here. talking about atg missiles?

**Comment by apotsepko** [comment]
Tesla towers, like engineers turrets inherit all player items. Sphere at top of tesla tower collide with ATG launched by Tesla tower
![20220812105220_2](https://user-images.githubusercontent.com/25206470/184310358-3dfe0a39-013c-47ed-8735-8e592b942228.jpg)
.

**Comment by TheTimeSweeper** [comment]
Ah yeah. This is fixed currently on my side, will be in the next update.
