### ISSUE TITLE
[RA2] some small issues

### ISSUE THREAD

**Issue by ApoGedon** [TheTimeSweeper/the#26]
hey @TheTimeSweeper thank you for this awesome red alert mod-pack!
The Chrono Legionnaire is instantly a new favorite, you can't imagine how often I refreshed thunderstore.io to see
if there is a new update after the DLC.

few small bugs I found:

-If the chrono legionnaire  uses chronosphere to teleport enemies way up high they often fall trough the ground,
don't take fall damage or give any credit. Same for trying to teleport enemies into pits. (i hope this is intended feature,
like in ra2 you could use chronosphere to drop enemies into water)

fixed: 
> the chrono i.v.a.n bomb timer vfx stays on the map and can be seen from everywhere / through walls

-desolator shift does only work as host in multiplayer

Again only minor issues, thanks again for this awesome mod!

**Comment by TheTimeSweeper** [comment]
fixed my issues. I believe the enemy issue is on gearbox's "enemies are not important so shittify their collision" solution so I will close this. thanks thanks for reporting
