### ISSUE TITLE
[RA2] Mod breaks some Deployable limits.

### ISSUE THREAD

**Issue by WolfoIsBestWolf** [TheTimeSweeper/the#27]
If I have this mod enabled I can only have 1 Captain Beacons and Forgive me Please projectile.
Also spawning a Forgive me Please projectile destroys captain beacons. (They both get added as ID 23 so I guess they're linked??)
They get added as the wrong ID of deployable (presumably counting as one of the mods)
Some other limits work fine like Engi Turrets.

I do not know if this is because the mod uses R2API wrong or if R2API.Deployables is at fault. 
But the issue does not happen with R2API on it's own.

**Comment by TheTimeSweeper** [comment]
fex
