### ISSUE TITLE
[Bug] Ancient Scepter'd Tesla Tower ally lacks a name?

### ISSUE THREAD

**Issue by Coffe-e** [TheTimeSweeper/the#6]
I haven't been able to upload images to github for a while for some reason, but I think I can describe it decently well here: When you pick up ancient scepter, and use the Tesla Tower skill, the ally's name is "TESLA_TOWER_SCEPTER..." or something along those lines. It's a small issue though so it's not a big deal.
I did run into some NREs with the tower earlier today, but i'm not sure what caused it, and i think it was a one-off so I'll get back to you on that if I run into it again.

**Comment by TheTimeSweeper** [comment]
fixed internally. thanks thanks
