### ISSUE TITLE
[Bug] Tesla Trooper's default utility bugged as of 2.0

### ISSUE THREAD

**Issue by Coffe-e** [TheTimeSweeper/the#7]
Currently, i'm experiencing an issue with Tesla trooper's default utility: The damage blocked portion of the effect functions as expected, but the explosion at the end ceases to trigger, and the electrical aura you gain visually from it stays. Here's a log for testing the mod alone/with aerolt.
[LogOutput.log](https://github.com/TheTimeSweeper/the/files/10202737/LogOutput.log)

**Comment by TheTimeSweeper** [comment]
feex
